name: Build

on: [push]

permissions: {}

jobs:
    lint-node:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@50fbc622fc4ef5163becd7fab6573eac35f8462e # v1
            - uses: actions/setup-node@f1f314fca9dfce2769ece7d933488f076716723e # v1
              with:
                  node-version: 12
            - name: Cache module
              uses: actions/cache@cffae9552bb9f84b9812c1ee9ea2e3c0a70a797e # v1.0.3
              with:
                  path: ~/.npm/
                  key: npm-cache
            - name: Install modules
              run: npm ci
